### ISSUE TITLE
Release version 0.11

### ISSUE THREAD

**Issue by ernestask** [abrt/will-crash#20]
Would it be possible to have a new release rolled? I’m particularly interested in https://github.com/sorki/will-crash/commit/675f376278bc2d70e9c3298ed9baebdd607b9220, but https://github.com/sorki/will-crash/commit/b0ad68759c7b68699910ba9f3f2fc5d00ed08d4e also seems useful.

**Comment by sorki** [comment]
Moving this to abrt org as I no longer care about this.
